[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.25'
optimizer = true
optimizer_runs = 1
fs_permissions = [
    { access = "read", path = "./script/input/"},
    { access = "read-write", path = "./script/output/"}
]
evm_version = 'cancun'
remappings = [
    '@layerzerolabs/oft-evm/=lib/devtools/packages/oft-evm/',
    'layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@layerzerolabs/lz-evm-messagelib-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/messagelib/',
    'solidity-bytes-utils/=lib/solidity-bytes-utils/',
]

[fuzz]
runs = 1000

[invariant]
runs = 1
depth = 100

[etherscan]
mainnet = { key = "${MAINNET_API_KEY}" }
optimism = { key = "${OPTIMISMSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
gnosis_chain = { key = "${GNOSISSCAN_API_KEY}", url = "https://api.gnosisscan.io/api" }
arbitrum_one = { key = "${ARBISCAN_API_KEY}" }
world_chain = { key = "${WORLD_CHAIN_API_KEY}", chain = 480, url = "https://worldchain-mainnet-explorer.alchemy.com/api" }
unichain = { key = "${UNICHAIN_API_KEY}", chain = 130, url = "https://unichain.blockscout.com/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
