name: deploy-protocol

on: workflow_dispatch

env:
  GOERLI_RPC_URL: ${{ secrets.GOERLI_RPC_URL }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  FOUNDRY_PROFILE: ci

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: make build
        id: build

      - name: Run Tests
        run: make test
        id: test

      - name: Generate ABIs
        uses: sergeysova/jq-action@v2.3.0
        id: extract-abi
        with:
          cmd: bash script/extractABI.sh

      - name: Deploy EtherFi Suite Contracts
        run: make deploy-goerli-suite
        id: deploy-goerli-suite

      - name: Get date
        id: get-date
        run: echo "DATE=$(date '+%Y-%m-%d--%H_%M')" >> $GITHUB_ENV

      - name: PR to contracts
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        with:
          source_folder: "release"
          destination_repo: "GadzeFinance/dappContracts"
          destination_base_branch: "master"
          destination_head_branch: "contract-deployment-triggered-${{ env.DATE }}"
          user_email: "bot@ether.fi"
          user_name: "Ether.Fi Github Bot"

      - name: PR to subgraph
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        with:
          source_folder: "release"
          destination_repo: "GadzeFinance/etherfi-subgraph"
          destination_base_branch: "master"
          destination_head_branch: "contract-deployment-triggered-${{ env.DATE }}"
          user_email: "bot@ether.fi"
          user_name: "Ether.Fi Github Bot"

      - name: PR to next-dapp
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        with:
          source_folder: "release"
          destination_repo: "GadzeFinance/etherfi-app"
          destination_folder: "src"
          destination_base_branch: "main"
          destination_head_branch: "contract-deployment-triggered-${{ env.DATE }}"
          user_email: "bot@ether.fi"
          user_name: "Ether.Fi Github Bot"
