[profile.default]
src = "contracts"
out = "out"
optimizer = true
optimizer_runs = 20000
libs = ["lib"]
solc_version = '0.8.20'
test = 'test/foundry'
cache_path = 'forge-cache'
fs_permissions = [{ access = "read", path = "./out"}]
evm_version = "shanghai"
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "forge-std/=lib/forge-std/src/",
  "ds-test/=lib/ds-test/src/"
]
[fmt]
tab_width = 2

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[fuzz]
runs = 2000