compressionLevel: mixed

enableGlobalCache: false
npmPublishAccess: "public" 

nodeLinker: node-modules

npmScopes:
  pendle:
    npmAlwaysAuth: true
    npmAuthToken: "${PENDLE_AUTH_TOKEN:-Missing access token}"
    npmPublishRegistry: "https://registry.npmjs.org/"
    npmRegistryServer: "https://registry.npmjs.org/"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
