[profile.default]
solc_version = "0.8.23"
src = "contracts"
out = "out"
libs = ["lib", "node_modules"]   # <- habilita usar node_modules como biblioteca
optimizer = true
optimizer_runs = 200

# Opcional: silenciar warnings de caminho/format
ignored_error_codes = [1878, 3420]